/**
 * @jest-environment node
 *
 * Payout generation used to be manual-only, so a month nobody generated by hand
 * produced no payout rows and the revenue was invisible everywhere. These tests
 * pin the catch-up behaviour that closes that gap.
 */

const {
  runPayoutGeneration,
  isEnabled,
  resolveCatchupMonths,
} = require('../utils/payoutScheduler');

function makeDb(createdPerMonth = {}) {
  return {
    generateMonthlyPayouts: jest.fn((year, month) => createdPerMonth[`${year}-${month}`] || 0),
  };
}

describe('payout scheduler configuration', () => {
  test('enabled by default in production', () => {
    expect(isEnabled({ NODE_ENV: 'production' })).toBe(true);
  });

  test('disabled by default outside production', () => {
    expect(isEnabled({ NODE_ENV: 'development' })).toBe(false);
  });

  test('explicit 0 disables even in production', () => {
    expect(isEnabled({ NODE_ENV: 'production', PAYOUT_SCHEDULER_ENABLED: '0' })).toBe(false);
  });

  test('explicit 1 enables outside production', () => {
    expect(isEnabled({ NODE_ENV: 'development', PAYOUT_SCHEDULER_ENABLED: '1' })).toBe(true);
  });

  test('catch-up window defaults to 6 months', () => {
    expect(resolveCatchupMonths({})).toBe(6);
  });

  test('catch-up window is configurable', () => {
    expect(resolveCatchupMonths({ PAYOUT_CATCHUP_MONTHS: '12' })).toBe(12);
  });

  test('invalid catch-up window falls back to the default', () => {
    expect(resolveCatchupMonths({ PAYOUT_CATCHUP_MONTHS: 'abc' })).toBe(6);
  });
});

describe('runPayoutGeneration', () => {
  test('never generates for the current (still open) month', () => {
    const database = makeDb();
    const now = new Date(2026, 6, 15); // July 2026

    runPayoutGeneration({ database, env: {}, now });

    const monthsCalled = database.generateMonthlyPayouts.mock.calls.map(([y, m]) => `${y}-${m}`);
    expect(monthsCalled).not.toContain('2026-7');
    expect(monthsCalled[0]).toBe('2026-6'); // starts at the previous month
  });

  test('walks back the full catch-up window', () => {
    const database = makeDb();
    const now = new Date(2026, 6, 15);

    runPayoutGeneration({ database, env: { PAYOUT_CATCHUP_MONTHS: '3' }, now });

    const monthsCalled = database.generateMonthlyPayouts.mock.calls.map(([y, m]) => `${y}-${m}`);
    expect(monthsCalled).toEqual(['2026-6', '2026-5', '2026-4']);
  });

  test('crosses the year boundary correctly', () => {
    const database = makeDb();
    const now = new Date(2026, 1, 10); // February 2026

    runPayoutGeneration({ database, env: { PAYOUT_CATCHUP_MONTHS: '3' }, now });

    const monthsCalled = database.generateMonthlyPayouts.mock.calls.map(([y, m]) => `${y}-${m}`);
    expect(monthsCalled).toEqual(['2026-1', '2025-12', '2025-11']);
  });

  test('backfills a month that was missed entirely', () => {
    // Only April has ungenerated revenue — it must still be picked up months later.
    const database = makeDb({ '2026-4': 3 });
    const now = new Date(2026, 6, 15);

    const summary = runPayoutGeneration({ database, env: {}, now });

    expect(summary.created).toBe(3);
    expect(summary.months).toEqual([{ year: 2026, month: 4, created: 3 }]);
  });

  test('one failing month does not stop the rest of the backfill', () => {
    const database = {
      generateMonthlyPayouts: jest.fn((year, month) => {
        if (month === 5) throw new Error('db locked');
        return month === 4 ? 2 : 0;
      }),
    };
    const now = new Date(2026, 6, 15);

    const summary = runPayoutGeneration({ database, env: { PAYOUT_CATCHUP_MONTHS: '3' }, now });

    expect(database.generateMonthlyPayouts).toHaveBeenCalledTimes(3);
    expect(summary.created).toBe(2); // April still generated despite May failing
  });

  test('repeat runs create nothing new (generation is idempotent)', () => {
    const database = makeDb();
    const now = new Date(2026, 6, 15);

    const first = runPayoutGeneration({ database, env: {}, now });
    const second = runPayoutGeneration({ database, env: {}, now });

    expect(first.created).toBe(0);
    expect(second.created).toBe(0);
  });
});
