/**
 * Canonical error codes for all API error responses.
 * Every res.status(N).json({ error, code }) must use one of these.
 * Clients can match on `code` for programmatic handling without parsing strings.
 */
module.exports = {
  // ── Auth ──────────────────────────────────────────────────────────────────
  AUTH_MISSING_FIELDS:        'AUTH_MISSING_FIELDS',
  AUTH_PASSWORD_TOO_SHORT:    'AUTH_PASSWORD_TOO_SHORT',
  AUTH_EMAIL_UNAVAILABLE:     'AUTH_EMAIL_UNAVAILABLE',
  AUTH_EMAIL_TAKEN:           'AUTH_EMAIL_TAKEN',
  AUTH_INVALID_CREDENTIALS:   'AUTH_INVALID_CREDENTIALS',
  AUTH_OWNER_NOT_CONFIGURED:  'AUTH_OWNER_NOT_CONFIGURED',
  AUTH_REGISTER_FAILED:       'AUTH_REGISTER_FAILED',
  AUTH_LOGIN_FAILED:          'AUTH_LOGIN_FAILED',

  // ── Queue ─────────────────────────────────────────────────────────────────
  QUEUE_VENUE_NOT_FOUND:      'QUEUE_VENUE_NOT_FOUND',
  QUEUE_INVALID_VOLUME:       'QUEUE_INVALID_VOLUME',
  QUEUE_DEVICE_REQUIRED:      'QUEUE_DEVICE_REQUIRED',
  QUEUE_DEVICE_ID_INVALID:    'QUEUE_DEVICE_ID_INVALID',
  QUEUE_INVALID_DIRECTION:    'QUEUE_INVALID_DIRECTION',
  QUEUE_RATE_LIMITED:         'QUEUE_RATE_LIMITED',
  QUEUE_SONG_MISSING_FIELDS:  'QUEUE_SONG_MISSING_FIELDS',
  QUEUE_SONG_TOO_LONG:        'QUEUE_SONG_TOO_LONG',
  QUEUE_PAYMENT_REQUIRED:     'QUEUE_PAYMENT_REQUIRED',
  QUEUE_SONG_DUPLICATE:       'QUEUE_SONG_DUPLICATE',
  QUEUE_USER_LIMIT_REACHED:   'QUEUE_USER_LIMIT_REACHED',
  QUEUE_READ_FAILED:          'QUEUE_READ_FAILED',
  QUEUE_REQUEST_FAILED:       'QUEUE_REQUEST_FAILED',
  QUEUE_PLAYING_FAILED:       'QUEUE_PLAYING_FAILED',
  QUEUE_PAUSE_FAILED:         'QUEUE_PAUSE_FAILED',
  QUEUE_ADVANCE_MISSING_SONG: 'QUEUE_ADVANCE_MISSING_SONG',
  QUEUE_ADVANCE_FAILED:       'QUEUE_ADVANCE_FAILED',
  QUEUE_SKIP_UNAUTHORIZED:    'QUEUE_SKIP_UNAUTHORIZED',
  QUEUE_SKIP_MISSING_SONG:    'QUEUE_SKIP_MISSING_SONG',
  QUEUE_SKIP_CONFLICT:        'QUEUE_SKIP_CONFLICT',
  QUEUE_SKIP_FAILED:          'QUEUE_SKIP_FAILED',
  QUEUE_REMOVE_UNAUTHORIZED:  'QUEUE_REMOVE_UNAUTHORIZED',
  QUEUE_REMOVE_FAILED:        'QUEUE_REMOVE_FAILED',

  // ── Vote ──────────────────────────────────────────────────────────────────
  VOTE_MISSING_FIELDS:        'VOTE_MISSING_FIELDS',
  VOTE_INVALID_VALUE:         'VOTE_INVALID_VALUE',
  VOTE_RATE_LIMITED_DOWN:     'VOTE_RATE_LIMITED_DOWN',
  VOTE_RATE_LIMITED_UP:       'VOTE_RATE_LIMITED_UP',
  VOTE_SONG_NOT_FOUND:        'VOTE_SONG_NOT_FOUND',

  // ── Payment ───────────────────────────────────────────────────────────────
  PAYMENT_MISSING_FIELDS:     'PAYMENT_MISSING_FIELDS',
  PAYMENT_VENUE_NOT_FOUND:    'PAYMENT_VENUE_NOT_FOUND',
  PAYMENT_NOT_REQUIRED:       'PAYMENT_NOT_REQUIRED',
  PAYMENT_INVALID_PRICE:      'PAYMENT_INVALID_PRICE',
  PAYMENT_NOT_CONFIGURED:     'PAYMENT_NOT_CONFIGURED',
  PAYMENT_PROVIDER_FAILED:    'PAYMENT_PROVIDER_FAILED',
  PAYMENT_INVALID_RESPONSE:   'PAYMENT_INVALID_RESPONSE',
  PAYMENT_CREATE_FAILED:      'PAYMENT_CREATE_FAILED',
  PAYMENT_CHECKOUT_REQUIRED:  'PAYMENT_CHECKOUT_REQUIRED',
  PAYMENT_CHECKOUT_INVALID:   'PAYMENT_CHECKOUT_INVALID',

  // ── Search ────────────────────────────────────────────────────────────────
  SEARCH_QUERY_REQUIRED:      'SEARCH_QUERY_REQUIRED',
  SEARCH_FAILED:              'SEARCH_FAILED',

  // ── Owner ─────────────────────────────────────────────────────────────────
  OWNER_OVERVIEW_FAILED:      'OWNER_OVERVIEW_FAILED',
};
